### PR TITLE
Minuit2 option is not required for ROOT minimizer factories

### PR DESCRIPTION
**Pull request by nadrino**

### CODE REVIEW

**Comment by ClarkMcGrew** [comment]
@nadrino How old of a ROOT are we willing to support.  The minuit2 requirement is dropped around 30ish (I'd have to look again for sure).  After that, it's the default minimizer, but before that it is an optional component.

**Comment by ClarkMcGrew** [comment]
BTW: It's not a standard component in the default T2K version of root.

**Comment by nadrino** [comment]
GUNDAM is only using `ROOT::Math::Factory::CreateMinimizer`, but not compiling with the option -DWith_Minuit2=ON does not prevent to use Minuit2 in this context. I think the available minimizers are independent of this option

**Comment by ClarkMcGrew** [comment]
BTW: I'm also using ROOT 6.32.02 (latest as a couple weeks) so on Linux, the extra check isn't causing trouble (yet).  Also, I thought we depended on some of the Minuit2 behavior for the minimizer.  Last time I checked, the minimizer factory doesn't do a great job of hiding the internals.

Truthfully, I'd just as soon drop it, but I think we need to validate older versions of ROOT without it.

**Comment by nadrino** [comment]
Without the check it still works down to ROOT v6.18.04

**Comment by ClarkMcGrew** [comment]
It passed all of the ctests?  Or is that a compilation test.

**Comment by ClarkMcGrew** [comment]
Where isn't it compiling?  I'm using the lastest root without -Dminuit2=on, and the feature is still provided by the ROOT cmake config.  Perhaps we need an explicit version check (if ROOT<6.x require miniuit2, otherwise, not).

**Comment by nadrino** [comment]
This is a CMake error within GUNDAM:

```
-- [INFO]: Looking for ROOT install...
-- [INFO]: [ROOT]: ROOT found.
-- [INFO]: [ROOT]: ROOT cmake use file /home/users/b/blancadr/install/root/cmake/ROOTUseFile.cmake
-- [INFO]: [ROOT]: ROOT include directory: /home/users/b/blancadr/install/root/include
-- [INFO]: [ROOT]: ROOT C++ Flags:  -std=c++17 -pipe -fsigned-char -pthread
-- [INFO]: [ROOT]: ROOT Version: 6.30.04
-- [INFO]: [ROOT]: Use >6.32 or rebuild root with-Dminuit2=on in the cmake command
CMake Error at cmake/utils/cmessage.cmake:28 (message):
  [ERRO]: [ROOT]: minuit2 is required
Call Stack (most recent call first):
  cmake/dependencies.cmake:109 (cmessage)
  CMakeLists.txt:25 (include)


-- Configuring incomplete, errors occurred!
make: *** [Makefile:884: cmake_check_build_system] Error 1
/home/users/b/blancadr/repo/gundam
```

This PR remove this check as it is not relevant to know if GUNDAM will be able to use the Minuit2 algorithm

**Comment by ClarkMcGrew** [comment]
We've required minuit2 since our validation was done with minuit2.  I guess 6.30 removed the minuit2, option, but didn't flag minuit2 as being available?  

My worry is that we have a lot of people on old versions of ROOT where minuit2 is not part of the standard build, and our validation used minuit2.  If we remove the check, I think we better check the old versions and make sure they still work validate, *OR* explicitly remove support for old versions.

**Comment by ClarkMcGrew** [comment]
How about changing that from an error to a (very loud) warning?

**Comment by nadrino** [comment]
We could, but my point is that I don't even think this check is relevant to know if Minuit2 is included in the ROOT::Math::Factory (even for older version of ROOT). So even having nothing at all should be alright

**Comment by ClarkMcGrew** [comment]
From a "will compile and run" point of view we may not need minuit2, but I think we also "will give the validated answer".   

How about changing dependencies.cmake 108 and 109 into WARNING (instead of STATUS and FATAL_ERROR).  That lets 6.30 work, and we can do more validity checks on old minuit (It will probably be OK, but...).

**Comment by nadrino** [comment]
The `--has-minuit` flag does not tell if GUNDAM will be able to run minuit, so even if it's set to false it should give the validated answer...

**Comment by ClarkMcGrew** [comment]
@nadrino This is a rogue merge, because you *still* have not addressed the issue of checking that the results are the same with minuit and minuit2.  It is *entirely* irrelevant whether the code compiles with minuit.

**Comment by nadrino** [comment]
Haha I wasn't sure about it, but I thought you agreed on the last message

**Comment by nadrino** [comment]
The ROOT::Math factory has Minuit and Minuit2 inside even without the `--has-minuit`

**Comment by ClarkMcGrew** [comment]
That is not true.    The old minuit was dropped in place of the minuit2 code base, and minuit2 became the default minimizer so the separate compilation was disabled.   Earlier versions of ROOT may not have minuit2 without explicitly enabling it's compilation.  The issue is that GUNDAM is validated with minuit2, not minuit, and if we want to support minuit will need to validate it separately.   *This has nothing to do with whether the code will compile and run.*

The correct solutions are: 1) validate classic minuit; 2) check for minuit2 (possibly as a warning, not a failure); or 3) remove support for ROOT before 6.28.  

The ROOT 6.30 line has a lot of bugs (it is not a "happy" release).  But, one of them is that it doesn't correctly set the HAS_MINUIT2 in the ROOT cmake config.  The flag is correctly set for 6.28 and 6.32.  If we are supporting 6.30, then the check for 6.30, and only 6.30, needs to be fixed.

**Comment by nadrino** [comment]
I confirm most of the tests passed on my computing cluster which uses ROOT v6.30 without the minuit2 option enabled. The only ones that failed are the one with the CacheManager because I don't enabled it in my GUNDAM build:

```
Failed Jobs:
FAILED: unexpected-failure:"/home/users/b/blancadr/repo/gundam/tests/fast-tests/200CovarianceFit-CacheManager.sh"
FAILED: unexpected-failure:"/home/users/b/blancadr/repo/gundam/tests/fast-tests/900CovarianceFitCheck-CacheManager.C"

FAIL: Tests failed
```

```
(cd output.2024-07-18-1327 && /home/users/b/blancadr/repo/gundam/tests/fast-tests/200CovarianceFit-CacheManager.sh /home/users/b/blancadr/repo/gundam/tests/fast-tests)
JOB FAILURE: fast-tests/200CovarianceFit-CacheManager.sh
/home/users/b/blancadr/install/gundam/bin/gundamFitter
/home/users/b/blancadr/repo/gundam/tests/output.2024-07-18-1327/200CovarianceFit-CacheManager.root
/home/users/b/blancadr/repo/gundam/tests/fast-tests/200CovarianceFit-config.yaml
terminate called after throwing an instance of 'std::runtime_error'
  what():  exception thrown by the logger:useCache: "GUNDAM compiled without Cache::Manager"
```

**Comment by ClarkMcGrew** [comment]
But 6.30 *does* use minuit2.  The test is whether and older ROOT (say 6.18) works with "-Dminuit2=off".  Passing the unit tests is a good start, but they only check for easy problems.

**Pull request merged**
