### PR TITLE
update from main

### PR DESCRIPTION
**Pull request by nadrino**

### CODE REVIEW

**Comment by ClarkMcGrew** [comment]
I just noticed the name of the branch.  "marginalise" Tool.  Are you doing MCMC work,  actually doing the (massive) integral, or is this really frequentist profiling (i.e. just finding the max likelihood vs some variable).    If it's not actual integration (MC or otherwise), it probably shouldn't be called marginalization.

**Comment by nadrino** [comment]
This is actually a frequentist profiling with weighting of the throws. This branch has been developped by @lgiannes, the original name was "bias tool" but it included a new app called `gundamMarginalize`.

**Comment by ClarkMcGrew** [comment]
Since it's not actual marginalization, maybe we should change the name of the app.  No use having it misnamed.

**Comment by nadrino** [comment]
Yeah definitely, I'll check with Lorenzo

**Comment by lgiannes** [comment]
The branch adds an app that takes as input the output of gundamFitter (with postfit covariance matrix) and generates a bunch of throws, saving the vector of parameters and the corresponding value of the likelihood for each throw. 
It was called marginalise because the output dataset was to supposed to be used to "do the massive integral" by means of importance sampling or normalizing flows. I agree that we can change the name, to something like "gundamSampler" or something?

**Pull request merged**
