### PR TITLE
Adding different options for PCA threshold

### PR DESCRIPTION
**Pull request by nadrino**

### CODE REVIEW

**Comment by riccioc** [comment]
The last five commits should go in another pull request since are completely unrelated. It is important to have properly documented pull requests so that we can find changes more easily.

**Comment by nadrino** [comment]
Moved those commits here: https://github.com/gundam-organization/gundam/pull/562

**Comment by nadrino** [comment]
If there's no objections, I'll merge by the end of the day

**Comment by riccioc** [comment]
I think the name `PcaMethod::SigmaThreshold` can be misleading because one could think that this method is using the cumulative percentage of the total variation. In this method, the parameters are kept starting with the largest eigenvalue until the cumulative percentage of the total variance meets or exceeds a specified threshold. Furthermore, the sqrt of the reduced chi2 isn't really connected with "sigma". Maybe you can just opt for `PcaMethod::SqrtReducedDeltaChi2Threshold`? BWT it would be useful to have also the method I described.

**Comment by nadrino** [comment]
I see what you mean. It make sense to change the name to `SqrtReducedDeltaChi2Threshold` then. For the cumulative percentage, it handled by another option. However we could think of a way to merge both

**Comment by nadrino** [comment]
I'll merge it soon if there no further comments

**Pull request merged**
