### PR TITLE
Don't display class names in release mode

### PR DESCRIPTION
**Pull request by nadrino**
Complementing Clark's logger modification with displaying the severity. This PR gets rid of all the LoggerInit setting the per-file user headers which were displaying the class names. This has become useless has this information is redundant with the severity and the filename.

### CODE REVIEW

**Comment by ClarkMcGrew** [comment]
Don't merge this.  It's the wrong direction since the file line should only be output during DEBUG compiles, and not during RELEASE.  Instead of modifying all of the files, just change the define in the cmake file.

**Review by ClarkMcGrew — CHANGES_REQUESTED** [review]
This is the wrong way to solve the problem, and is removing information that current parsing scripts need.   The commit should be removed.

**Comment by nadrino** [comment]
I think there is a misunderstanding, the filename and line are only displayed in the DEBUG mode. The RELEASE binaries will be showing only the date and the severity

**Comment by nadrino** [comment]
I've removed the `LoggerInit` instructions as they are hard to maintain, execute before the `main()` is running (no error catching), and is useless now

**Comment by nadrino** [comment]
@ClarkMcGrew What do you mean by `current parsing scripts need`?

**Comment by ClarkMcGrew** [comment]
The change for RELEASE is wrong since the information you are removing isn't redundant.  This is used in log file parsing to search for specific output.

As far as removing the LoggerInit calls.  Those have negligible effect on the runtime, and remove useful feature that can be enabled or disabled from the compilation line.

**Comment by nadrino** [comment]
I see, so you want to have an indication in RELEASE mode for where the piece of log is triggered. I could add a preset in the Logger to display the filename (without the extension). It would do the same but at least would more maintainable as a change in filename would be automatically handled

**Comment by ClarkMcGrew** [comment]
Actually, the main library changes aren't improving the code quality, aren't providing new capability, and are removing functionality.   The current capabilities should be left alone, and if new capability is required, implemented with minimal changes.  It's good to clean up the BUILD_TYPE handling, but why remove the information form the LOGGER_ERROR_PREFIX?

As of now, the logging code needs a lot of work since it's slow and missing important features, and small changes aren't going to fix it.  But, it's not a top priority, and is tricky since it needs remain source compatible.  The big Logger problems are: 1) no global log level that can be set at run time (and from the command line);    2) log operations instantiate an object, even when not producing output;  3) content is generated even when it will be discarded; 4) logging doesn't interact well with exceptions when output is buffered (for instance when writing to a log file, errors and warnings should be unbuffered, or at least fully flushed).; and, 5) no unified interface for run-time control for the log level in different components (propagator, vs likelihood, vs etc).

**Pull request closed without merging**
